import type { Language } from "@/data/content";
import type { StandEvent } from "@/lib/stand-events";

export type { StandEvent };

/**
 * Lo que dice el mini Stand.
 *
 * Su personalidad: un Stand dramatico y algo creido que narra la pagina
 * como si fuera un capitulo de JoJo. Habla de "el" (su usuario), exagera
 * todo con tension de manga (ゴゴゴ, ドドド) y suelta referencias distintas
 * de las nueve partes, no siempre la misma.
 *
 * Reglas: frases cortas (en celular solo salen las de 30 letras o menos),
 * barajadas sin repetir, nunca explica los secretos, y nada inventado
 * sobre el trabajo: lo que dice de Cris sale de lo que la pagina ya dice.
 */

export type PowerId =
  | "zawarudo"
  | "starplatinum"
  | "crazydiamond"
  | "goldexperience"
  | "echoes"
  | "softwet"
  | "hermit"
  | "madeinheaven"
  | "bitesthedust"
  | "kingcrimson";

/** Lugares a los que el Stand sabe llevarte desde la conversacion. */
export type GuideId = "projects" | "sites" | "pricing" | "contact";

export interface PowerLines {
  name: string;
  jp: string;
  say: string[];
  done: string[];
  /** Lo que dice si el poder sale "redondo" (p. ej. reventar todas las burbujas). */
  bonus?: string[];
  /** Frases propias de cada variante del poder (si no hay, usa say/done). */
  variants?: Record<string, { say: string[]; done?: string[] }>;
}

export interface StandLines {
  label: string;
  spots: Record<string, string[]>;
  outro: string[];
  sleep: string;
  wake: string[];
  home: string[];
  night: string;
  console: string;
  /** Saludo al salir del retrato, segun la hora (la madrugada es secreto). */
  greetings: { morning: string[]; afternoon: string[]; evening: string[]; visit: string[] };
  /** Lo que dice solo, posado, si lleva rato callado. */
  musings: string[];
  /** Golpe de efecto al posarse (se pinta como onomatopeya). */
  landing: string[];
  events: Record<StandEvent, string[]>;
  /**
   * Tiempo detenido (toque en el retrato o ZA WARUDO): el Stand es el
   * unico que se mueve. sections: burlas segun donde ocurre (ids de
   * data-spot, "hero" y "default"); attempt: si intentas moverte;
   * resume: cuando el tiempo vuelve a correr.
   */
  timeStop: { sections: Record<string, string[]>; attempt: string[]; resume: string[] };
  chat: {
    title: string;
    close: string;
    greet: string[];
    greetAgain: string[];
    options: { who: string; cris: string; guide: string; trivia: string; power: string; janken: string; bye: string };
    who: string[][];
    cris: string[];
    trivia: string[];
    guidePrompt: string[];
    guide: Record<GuideId, { label: string; say: string[] }>;
    powerPrompt: string[];
    bye: string[];
    back: string;
  };
  powers: Record<PowerId, PowerLines>;
  /** Hermit Purple: lo que "ve" de la visita. {min}, {parts}, {total}, {secrets}, {visits}. */
  hermit: string[];
  /** Hermit Purple: rotulo de la foto de espiritu. */
  hermitPhoto: { title: string; time: string; parts: string; secrets: string; visits: string };
  /** Bites the Dust: al volver, el Stand repite su ultima frase con esto delante. */
  dejaVu: string[];
  /** Made in Heaven: el universo anterior (la pagina vieja) y el Stand frenandolo. */
  universe: { label: string; tagline: string; badge: string; loading: string; stop: string[] };
  janken: {
    title: string;
    intro: string[];
    hands: { rock: string; paper: string; scissors: string };
    call: string;
    win: string[];
    lose: string[];
    draw: string[];
    matchWin: string[];
    matchLose: string[];
    score: string;
    again: string;
    close: string;
    quit: string[];
  };
}

export const standLines: Record<Language, StandLines> = {
  es: {
    label: "Mini Stand: hablar con él",
    spots: {
      sites: [
        "Todas en línea. Ninguna en obra.",
        "Toca una. No muerden.",
        "Él las hizo. Yo vigilé.",
        "Esta tira la ordené yo.",
        "Cero plantillas. Todas a medida.",
        "¿Ves la del bebé? Adorable.",
        "Míralas. Ninguna se repite.",
        "Ábrela. Está en línea de verdad.",
        "Cada una, su propio Stand.",
        "Reales. Con dominio y todo.",
        "Un hotel en Santa Marta. Sí.",
        "Hasta una peluquería canina. Guau.",
        "Licorera 24/7. Yo no bebo.",
        "Camionetas en Barrancabermeja. ブロロロ.",
        "Ocho páginas. Ocho capítulos.",
        "Zapatos, bebés, perros. Variedad.",
      ],
      audit: [
        "Pega tu link. Sin miedo.",
        "Gratis. Sospechoso, ¿no?",
        "Tu página me está mirando.",
        "Revisa. Yo no juzgo. Mucho.",
        "Seis puntos. Como mis dedos.",
        "Daga kotowaru… no, dale.",
        "Mi Hermit Purple también revisa.",
        "Si sale rojo, no fui yo.",
        "Te lo dice en segundos.",
        "Un chequeo. Como el de Joseph.",
        "¿Lenta? Lo vamos a saber.",
        "Nada se guarda. Promesa de Stand.",
        "Tu página contra mi ojo. ゴゴゴ.",
      ],
      about: [
        "Ese es mi usuario.",
        "Una flecha y aquí estamos.",
        "Él escribe. Yo existo.",
        "Ingeniero y editor. Yo, Stand.",
        "Seguridad primero. Y yo segundo.",
        "Lee despacio. Hay tensión.",
        "Su sueño es mejor que el de Giorno.",
        "Destino: Bucaramanga.",
        "Aquí empieza su Bizarre Adventure.",
        "Revisa cerraduras. Hasta las mías.",
        "Dirige carpy. Yo dirijo nada.",
        "Logo, colores, contenido. Todo.",
        "32K en TikTok. Yo tengo 0.",
        "Este capítulo es el origen.",
      ],
      standcard: [
        "Ese soy yo. Más alto en persona.",
        "Potencial A. Modestia C.",
        "Velocidad B. Estoy entrenando.",
        "No le crean al hexágono.",
        "Mi mejor ángulo. Ese.",
        "Paranoid Android. Sí, la canción.",
        "Toca la flecha. Si te atreves.",
        "Alcance A: toda la página.",
        "Precisión A. Puntería, ni idea.",
        "Poder C. Es humildad.",
        "Resistencia A. Aguanto tus clics.",
        "Mi tarjeta. Mi orgullo.",
        "Esa flecha me hizo. Respeto.",
      ],
      github: [
        "Cada columna es un día.",
        "Golpéalas. Les gusta.",
        "Agosto despertó algo.",
        "La más alta la puse yo.",
        "ゴゴゴゴゴ…",
        "Commit tras commit. ORA.",
        "Gíralo. Desde atrás se ve épico.",
        "Columnas que suben. Como yo.",
        "Un día sin commits: yare yare.",
        "Cada cubo, un ORA.",
        "Toca una y te dice el día.",
        "Esto es un tablero de batalla.",
        "Las doradas brillan por algo.",
      ],
      services: [
        "Elige uno. O todos.",
        "Nada de plantillas.",
        "Todo a mano. Bueno, a teclado.",
        "Abre uno. Yo espero.",
        "¿Otra cosa? Pregúntale.",
        "Del logo al servidor. Todo.",
        "Cada servicio, su capítulo.",
        "¿Video también? Sí. Él edita.",
        "Más útil que un Stand de tiempo.",
        "Webs, software, video. Trío.",
        "Esto es como elegir Stand.",
        "Abre el que necesitas. Solo ese.",
      ],
      projects: [
        "Tres capítulos. Sin relleno.",
        "El capítulo 2 es mi favorito.",
        "Spoiler: terminan bien.",
        "Esto no es anime. Es real.",
        "Cambia de pestaña. Hay más.",
        "Capturas reales. Sin trucos.",
        "Al terminar: To be continued.",
        "El capítulo 3 tampoco está mal.",
        "Esto lo vio King Crimson. Todo.",
        "Actas encontradas en segundos.",
        "Cada caso, una pelea ganada.",
        "Lee el capítulo entero. Vale.",
      ],
      pricing: [
        "Precios a la vista.",
        "Más barato que una flecha.",
        "El del medio es el elegido.",
        "Nigerundayo… no, quédate.",
        "Lo final se acuerda antes.",
        "Lo que va aparte, está escrito.",
        "Speedwagon aprobaría estos precios.",
        "Sin letra chica. Ni ゴゴゴ.",
        "Elige con calma. Yo no presiono.",
        "El dominio va a tu nombre.",
        "Sin sorpresas. Salvo yo.",
        "Compara. Yo sostengo la tabla.",
      ],
      faq: [
        "Pregunta lo que sea.",
        "Leí todas. Dos veces.",
        "¿No está? Escríbele.",
        "Ábrelas. No explotan.",
        "Cortas y al grano.",
        "Mis respuestas: ORA. Las de él, mejores.",
        "Si dudas, abre otra.",
        "Hermit Purple ya las leyó.",
        "Trabaja con toda Colombia. Y más.",
        "Español o inglés. Ambos.",
        "Aquí no hay preguntas tontas.",
      ],
      contact: [
        "Escribe. Yo le aviso.",
        "Suele responder el mismo día.",
        "Un mensaje. Solo uno.",
        "WhatsApp o correo. Tú eliges.",
        "Ya llegaste hasta aquí…",
        "Dilo sin miedo. ゴゴゴ.",
        "Él lee todo. Yo también.",
        "Aquí se cierra el capítulo.",
        "Tu turno. Yo ya hablé mucho.",
        "Escribir no cuesta. Es gratis.",
        "Cuenta tu idea. Él la arma.",
        "El destino te trajo aquí.",
      ],
      tbc: [
        "To be continued…",
        "Fin de la Parte 9.",
        "Arrivederci. O no.",
        "Sube. Hay más.",
        "Suena Roundabout, ¿la oyes?",
        "La flecha apunta arriba. Sube.",
        "Fin. O un nuevo comienzo.",
        "Siguiente parte: tú escribes.",
        "Créditos. Quédate a la escena extra.",
      ],
    },
    outro: [
      "¿No te cansas? Yo sí.",
      "Se me acabaron. Muda.",
      "Desde el principio. Yare yare.",
      "Ya dije todo aquí. Muévete.",
      "Repetir es de Bites the Dust.",
    ],
    sleep: "z z z",
    wake: [
      "¡No estaba dormido!",
      "Meditaba. Hamon.",
      "¿Eh? ¿Volviste?",
      "Pausa estratégica.",
      "Me paré el tiempo a mí mismo.",
      "Soñé con un capibara.",
      "¡Despierto! ¿Qué me perdí?",
      "Soñaba que era Star Platinum.",
      "Cinco minutos más… no. Listo.",
      "Recargando energía de Stand.",
      "¿Dormido? Era una pose.",
    ],
    home: ["En casa.", "Al retrato.", "Aquí se está bien.", "De vuelta al origen.", "Mi rincón favorito.", "Cuido el retrato."],
    night: "Turno de noche. Como DIO.",
    console: "¿Me llamaste? Nadie hace eso.",
    greetings: {
      morning: [
        "Buenos días. ¿Café o Hamon?",
        "Temprano. Como Jonathan.",
        "Mañana. El sol ya salió. Ugh.",
        "Madrugaste. Respeto.",
        "Buen día. Respira. Hamon.",
      ],
      afternoon: [
        "Buenas tardes. Hora de leer.",
        "Tarde de Stands. Buena elección.",
        "Siesta cancelada. Vamos.",
        "Tarde perfecta para un capítulo.",
        "Buenas. ¿Almorzaste? Yo no como.",
      ],
      evening: [
        "Buenas noches. Hora de Stands.",
        "De noche se lee mejor.",
        "La noche cae. Yo despierto.",
        "Hora de DIO. Digo, de leer.",
        "Noche. Ambiente perfecto. ゴゴゴ.",
      ],
      visit: [
        "Volviste. Visita {n}.",
        "Visita {n}. Ya eres familia.",
        "{n} visitas. Sospechoso. Me gusta.",
        "Visita {n}. Como un Joestar más.",
        "Otra vez tú. Visita {n}.",
      ],
    },
    musings: [
      "¿Sabías que no tengo piernas?",
      "Me pregunto qué haría Jotaro aquí.",
      "Este diseño tiene buena pose.",
      "Huele a ゴゴゴ por aquí.",
      "Si me tocas, hablamos.",
      "Pienso, luego Stand.",
      "Un día seré parte del anime.",
      "Sigo aquí. Por si acaso.",
      "Hora de una pose. ¿Lista? No.",
      "¿Y si paro el tiempo? Pídemelo.",
      "Puedes lanzarme. No lo hagas.",
      "Mi diamante brilla solo.",
      "Tengo diez poderes prestados.",
      "¿Probaste Soft & Wet? Burbujas.",
      "Me aburro. Rompo algo, ¿sí?",
      "Si me arrastras, me mareo.",
      "Cada sección tiene su ambiente.",
      "Ya leí todo esto. Tres veces.",
      "Este pixel es mi mejor lado.",
      "Shh. Siento un enemigo Stand.",
    ],
    landing: ["ドン!", "ドドド", "バァーン", "ゴゴゴ", "ズン", "ドーン", "シュタッ", "ババーン"],
    events: {
      timestop: [
        "¡No me pude mover…!",
        "¿Quién paró el tiempo? ¿Tú?",
        "Me congelaste. Rencor eterno.",
        "Ni yo me salvo de ese reloj.",
        "¡Eso solo lo hace DIO!",
        "Cinco segundos sin existir. Ugh.",
      ],
      ora: ["¡ORA ORA ORA!", "¡Eso! Más fuerte.", "¿Escribiste ora? Respeto.", "Jotaro estaría orgulloso.", "¡ORAAA! Así se escribe."],
      muda: ["¿MUDA? Eso es de DIO.", "Traidor.", "Wryyyy… no, perdón.", "Muda muda… ¿Giorno, eres tú?", "Escribes como villano."],
      tbc: ["To be continued…", "¿Ya? ¿Así termina?", "Roundabout sonando.", "La flecha. Siempre la flecha.", "Fin de temporada."],
      barrage: ["¡Esa es la ráfaga!", "Seis golpes. Nada mal.", "Las columnas lloran.", "¡ORA a los commits!", "Esa columna no se recupera."],
      arrow: ["¡Esa flecha! Así nací yo.", "Cuidado con eso. Pica.", "Otro Stand no, por favor.", "La flecha elige. Te eligió.", "¿Despertaste algo? ゴゴゴ."],
      themeLight: ["¡Mis ojos! ¡La luz!", "¿Modo día? Soy de noche.", "Esto es el sol de DIO… no.", "Brilla. Como mi diamante.", "Ugh. Hamon puro."],
      themeDark: ["Mejor. La noche es mía.", "Así sí. Oscuro y elegante.", "Ahh. Paz.", "Vuelve la noche. Wryyy.", "Mis pixeles respiran."],
      language: ["Cambio de idioma. Interesante.", "Hablo los dos. Obvio.", "Bilingüe. Como él.", "Otro idioma. Mismo Stand."],
      whatsapp: ["¡Eso! Escríbele.", "Buena decisión. ゴゴゴ.", "Yo le aviso que vas.", "¡Ese es el espíritu!", "Destino sellado. ドン!"],
      copy: ["¿Copiando? Respeto.", "Llévatelo. Es gratis.", "Ctrl+C. Clásico.", "Echoes ya lo grabó.", "Copiado. Como un Stand gemelo."],
      return: ["¿Dónde estabas?", "Te esperé. Quieto.", "Volviste. Sabía.", "¿Otra pestaña? Celos.", "King Crimson borró tu ausencia."],
      fastScroll: ["¡Más despacio! Me mareo.", "¡Oye! Esto no es Speed King.", "Wooo… ¿por qué tan rápido?", "¿Made in Heaven o qué?", "¡Me dejas atrás!"],
      stare: ["¿Qué miras?", "Sí, soy yo.", "Tócame si te atreves.", "¿Oh? ¿Te acercas a mí?", "Mirada de Joestar. Lo sé."],
      audit: ["Revisando… ゴゴゴ.", "A ver esa página…", "Hermit Purple, ¡muéstrame!", "Analizando. No te muevas."],
      sent: ["¡Enviado! Él te responde.", "Mensaje entregado. Bien.", "Ahora a esperar. Yo espero contigo.", "¡Perfecto! ドン!", "Ya está. El destino se mueve."],
      bottom: ["Llegaste al final. Respeto.", "Leíste todo. Eres de los míos.", "Fin del volumen. Bien.", "Todo leído. Medalla Joestar."],
      chapter: ["¡Capítulo nuevo!", "Siguiente episodio. ドン!", "Oh, buen capítulo.", "Ese caso me gusta.", "Pasa la página. ペラ."],
      faq: ["Buena pregunta.", "Esa también me la hice.", "Ábrela toda. Es corta.", "Respuesta desbloqueada.", "Curiosidad de Joestar."],
      hesitate: ["¿Dudando? Dale.", "Ese botón no muerde.", "Un clic. Yo te cubro.", "Valor. Como Jonathan.", "Nigerundayo… no. Clic."],
      typing: ["Escribe. No miro.", "Tómate tu tiempo.", "Eso. Sin miedo.", "Tecleas como ORA.", "Echoes escucha. Tranquilo."],
      resize: ["¿Me encoges? Oye.", "La página se estira. Yo no.", "¿The Hand? Se movió todo.", "Ventana nueva. Mismo yo."],
      thrown: ["¡WRYYYYY!", "¡Oye! ¡Me mareo!", "¡No soy una pelota!", "Todo da vueltas…", "¡Nigerundayo… ah!", "¡Bájame, humano!"],
      dropped: ["¡Bájame! Ah, ya.", "Aterrizaje elegante.", "¿Me moviste? Valiente.", "Gracias por el viaje.", "Bonita vista desde aquí."],
    },
    timeStop: {
      sections: {
        hero: ["Toqué tu retrato. No lo viste.", "Me paseé por el hero. Quieto todo.", "Ni el WhatsApp se movió. Yo sí."],
        sites: ["Revisé las ocho páginas. Tú, quieto.", "Visité todas. No me viste.", "La tira se detuvo. Yo no."],
        audit: ["Auditaba mientras no podías.", "Tu link esperó. Yo no.", "Pausé el análisis. Muda."],
        about: ["Leí su historia entera. Ya.", "Ni él se movió. Yo sí.", "Cambié de sitio. ¿Lo notaste?"],
        standcard: ["Velocidad B… y aun así me moví.", "Le hice una pose a la flecha.", "Mi tarjeta y yo. Los únicos."],
        github: ["Ni un commit se movió.", "Conté las columnas. Todas.", "Tablero quieto. Yo libre."],
        services: ["Elegí uno por ti. Mentira.", "Los servicios esperaron. Yo no.", "Pausa de servicio. Ja."],
        projects: ["Pausé el capítulo. Leí el final.", "El caso se detuvo. Yo no.", "Ni King Crimson se movió."],
        pricing: ["Congelé los precios. Literal.", "Ningún precio subió. De nada.", "Toqué la tabla. No lo viste."],
        faq: ["Leí todas las respuestas. Ya.", "Las preguntas no se abrieron.", "Pausé la curiosidad."],
        contact: ["Tu mensaje esperó. Quieto.", "Ni el formulario parpadeó.", "Ya llegué. Tú no."],
        tbc: ["To be… paused.", "La flecha no avanzó.", "Roundabout en pausa."],
        default: ["Nadie se movió. Salvo yo.", "Solo yo en ese mundo.", "Muda muda. Estabas quieto.", "¿Viste algo? No. Nada."],
      },
      attempt: [
        "Intentaste moverte. Lo vi.",
        "Tu dedo no respondió, ¿eh?",
        "Muda. Te vi intentarlo.",
        "¿Querías hacer scroll? Ternura.",
        "Ni un pixel. Lo intentaste.",
      ],
      resume: ["そして時は動き出す。", "Y el tiempo se mueve.", "¿Me moví? Nunca.", "Siempre estuve aquí.", "Tiempo, sigue.", "Nueve segundos. Récord personal."],
    },
    chat: {
      title: "Paranoid Android",
      close: "Cerrar la conversación",
      greet: [
        "¿Oh? ¿Me hablas a mí?",
        "Un humano me tocó. ¿Qué quieres?",
        "Habla. El tiempo corre. Salvo que lo pare.",
        "¿Sí? Estaba posando.",
        "¡Ah! Un visitante valiente.",
        "Paranoid Android, a tu servicio.",
        "Me tocaste. Ahora somos aliados.",
        "¿Necesitas un Stand? Aquí estoy.",
      ],
      greetAgain: [
        "¿Otra vez tú? Me caes bien.",
        "Volviste. Sabía que lo harías.",
        "Nuestro destino era hablar de nuevo.",
        "Ya somos amigos, ¿no?",
        "Tú otra vez. ゴゴゴ. Bienvenido.",
      ],
      options: {
        who: "¿Quién eres?",
        cris: "Háblame de él",
        guide: "Llévame a…",
        trivia: "Algo de JoJo",
        power: "Usa un poder",
        janken: "Juguemos jan-ken",
        bye: "Nada, sigue",
      },
      who: [
        ["Soy Paranoid Android.", "El Stand de Cristian.", "Nací de una flecha. Larga historia."],
        ["Un Stand. Espíritu hecho poder.", "Él programa. Yo existo con estilo."],
        ["Me dicen PA.", "Bueno, nadie me dice nada.", "Tú puedes ser el primero."],
        ["Vivo en esta página.", "Duermo en el retrato.", "Y me poso en lo que lees."],
        ["Tengo poderes prestados.", "Ninguno es mío, técnicamente.", "Pero los uso con estilo."],
        ["Mi diamante es mi corazón.", "Diamond is Unbreakable.", "Yo tampoco. Creo."],
      ],
      cris: [
        "Hace páginas, software y video.",
        "Vive en Bucaramanga. Trabaja remoto.",
        "Cofundó carpy, un estudio de software.",
        "Viene de ciberseguridad. Revisa cerraduras.",
        "Tiene más de 32K seguidores con contenido propio.",
        "Trabaja en español y en inglés.",
        "Le escribes por WhatsApp y suele responder el mismo día.",
        "Tiene ocho páginas web en línea para negocios.",
        "Hizo la de un hotel en Santa Marta.",
        "Trabaja con negocios de toda Colombia y de afuera.",
        "El dominio y el hosting quedan a nombre del cliente.",
        "Usa la herramienta que pide el problema, no la costumbre.",
        "Hace también logo, colores y contenido.",
        "Hizo un buscador de actas que las encuentra en segundos.",
        "Habla por WhatsApp o por videollamada.",
      ],
      trivia: [
        "JoJo empezó en 1987. Araki no envejece. Sospechoso.",
        "Desde la Parte 4, los Stands se llaman como canciones.",
        "Yo me llamo como una canción de Radiohead. Tradición.",
        "La pose JoJo tiene nombre: JoJo-dachi.",
        "ゴゴゴ es el sonido de la tensión. Literal.",
        "Los Joestar nacen con una estrella en el hombro.",
        "DIO pasó cien años dormido en el fondo del mar.",
        "El Hamon se aprende respirando. Yo no respiro.",
        "Roundabout de Yes cerraba el anime. To be continued.",
        "Jotaro dice yare yare daze cuando algo le fastidia.",
        "Speedwagon se retira con estilo. Siempre.",
        "Killer Queen se llama como una canción de Queen.",
        "Bites the Dust: otra canción de Queen.",
        "Crazy Diamond viene de Pink Floyd.",
        "Kira solo quería una vida tranquila. Ajá.",
        "Josuke se enoja si hablan mal de su peinado.",
        "Los Stands solo los ven otros usuarios de Stand.",
        "Joseph adivina lo que vas a decir. Siempre.",
        "Gold Experience le da vida a lo que toca.",
        "La Parte 3 tiene Stands de cartas del tarot.",
        "Rohan dibuja más rápido que tú lees esto.",
        "Polnareff tiene el peinado más alto de JoJo.",
      ],
      guidePrompt: ["¿A dónde? Yo vuelo, tú miras.", "Elige destino. Agárrate.", "¿A dónde vamos, compañero?", "Destino. Elige con cuidado."],
      guide: {
        projects: { label: "Sus proyectos", say: ["¡A los capítulos!", "Proyectos. Sujétate.", "Vamos a los casos. ドン!"] },
        sites: { label: "Las páginas", say: ["Páginas en línea. ¡Vamos!", "A la tira de páginas.", "Ocho sitios. ¡Vuela!"] },
        pricing: { label: "Los precios", say: ["Precios. Sin miedo.", "Vamos a lo concreto.", "A la tabla. Respira."] },
        contact: { label: "Hablar con él", say: ["¡Al contacto! ドン!", "Buena decisión. Vamos.", "Directo a él. ¡Vamos!"] },
      },
      powerPrompt: [
        "Tengo poderes prestados. Elige.",
        "Elige. No me hago responsable.",
        "¿Cuál? Todos son peligrosos.",
        "Diez Stands en uno. Elige.",
        "Escoge. Yo pongo la pose.",
      ],
      bye: ["Arrivederci.", "Me voy a posar por ahí.", "Yare yare. Adiós.", "Nos vemos en el próximo capítulo.", "Sayonara. ゴゴゴ.", "Aquí estaré. Posando."],
      back: "Otra cosa",
    },
    powers: {
      zawarudo: {
        name: "ZA WARUDO",
        jp: "時よ止まれ",
        say: ["¡ZA WARUDO!", "¡ZA WARUDO! ¡Toki yo tomare!", "Mi mundo. ¡ZA WARUDO!"],
        done: ["Y el tiempo vuelve a moverse.", "そして時は動き出す。", "¿Viste algo? No, nada.", "Cinco segundos míos."],
      },
      starplatinum: {
        name: "Star Platinum",
        jp: "オラオラ",
        say: ["¡ORA ORA ORA ORA!", "Star Platinum… ¡ORA!"],
        done: ["Yare yare daze.", "Ráfaga completa. Nada roto.", "Así golpea Jotaro. Más o menos."],
        variants: {
          rush: { say: ["¡ORA ORA ORA ORA!", "Star Platinum… ¡ORA!", "¡Rush de ORAs!"], done: ["Yare yare daze.", "Quedó abollado. Se arregla solo.", "Ráfaga completa."] },
          finger: { say: ["¡Star Finger!", "Star Platinum… ¡dedo estelar!"], done: ["Un dedazo preciso.", "Precisión A. Ya ves."] },
          world: { say: ["¡Star Platinum: The World!", "Yo también paro el tiempo."], done: ["Un segundo mío.", "Igual que DIO. Pero bueno."] },
        },
      },
      crazydiamond: {
        name: "Crazy Diamond",
        jp: "ドラララ",
        say: ["¡DORARARARA!", "Crazy Diamond… ¡DORA!", "¡Doraaaa!"],
        done: ["Roto y arreglado. Como nuevo.", "Crazy Diamond lo deja mejor.", "¿Qué le dijiste a mi peinado?", "Todo en su sitio. Casi."],
      },
      goldexperience: {
        name: "Gold Experience",
        jp: "生命を",
        say: ["Gold Experience. ¡Vida!", "Yo, Giorno… no. Pero casi."],
        done: ["La página está viva. Literal.", "Vida para todos."],
        variants: {
          garden: { say: ["Gold Experience. ¡Vida!", "¡Que florezca todo!"], done: ["Mariquitas incluidas. De nada.", "Primavera instantánea."] },
          tree: { say: ["Gold Experience… ¡un árbol!", "¡Crece!"], done: ["Un árbol entero. Fotosíntesis.", "Ese árbol ya da sombra."] },
          frog: { say: ["Esa caja… ¡será una rana!", "Gold Experience. ¡Ribbit!"], done: ["Era una caja. Ahora salta.", "La rana volvió a ser caja. Tranquilo."] },
          butterflies: { say: ["¡Mariposas! Vida pura.", "Gold Experience… ¡a volar!"], done: ["Se fueron volando. Libres.", "Pura vida. Literal."] },
          snake: { say: ["Ese título… ¡serpiente!", "Gold Experience. Sssss."], done: ["Volvió a ser título. Ufff.", "No muerde. Creo."] },
        },
      },
      echoes: {
        name: "Echoes",
        jp: "エコーズ",
        say: ["¡Echoes! Sonidos pegados."],
        done: ["Ahora la página suena.", "Se despegan solos. Tranquilo."],
        variants: {
          act1: { say: ["¡Echoes ACT 1! Sonidos vivos.", "Pego sonidos. Mira cómo suenan."], done: ["La página habló. Literal.", "Sonidos devueltos."] },
          act2: { say: ["¡ACT 2! Tócalos. Suenan.", "Echoes ACT 2. Pisa uno."], done: ["¿Los tocaste todos? Bien.", "Se despegaron. Silencio."] },
          act3: { say: ["¡ACT 3! ¡3 FREEZE!", "S-H-I-T… digo, ¡3 FREEZE!"], done: ["Pesado, ¿eh? Ya pasó.", "Volvió a pesar normal."] },
        },
      },
      softwet: {
        name: "Soft & Wet",
        jp: "シャボン",
        say: ["Soft & Wet. ¡Burbujas ladronas!", "Burbujas. Roban cosas. Revéntalas."],
        done: ["Se llevaron cosas. Ya las devolví.", "Burbujas libres. Todo devuelto."],
        bonus: ["¡Todas! Recuperaste todo.", "Ninguna escapó. Gappy estaría orgulloso.", "Reventaste todo. Ladrón de ladronas."],
      },
      hermit: {
        name: "Hermit Purple",
        jp: "ハーミット",
        say: ["Hermit Purple… a ver qué veo.", "¡Hermit Purple! Foto de espíritu."],
        done: ["Foto revelada. Guárdala en tu memoria.", "Joseph estaría orgulloso."],
      },
      madeinheaven: {
        name: "Made in Heaven",
        jp: "時は加速する",
        say: ["¡Made in Heaven! El tiempo acelera.", "Made in Heaven… ¡más rápido!"],
        done: ["Uf. Universo salvado.", "Este universo se queda.", "Casi volvemos al rojo. Nunca más."],
      },
      bitesthedust: {
        name: "Bites the Dust",
        jp: "負けて死ね",
        say: ["Killer Queen… ¡Daisan no bakudan!", "Killer Queen… ¡Bites the Dust!"],
        done: ["El tiempo retrocedió. Nadie lo notó.", "¿Déjà vu? Normal.", "Another one bites the dust."],
      },
      kingcrimson: {
        name: "King Crimson",
        jp: "キング・クリムゾン",
        say: ["¡King Crimson!", "King Crimson… borra el tiempo."],
        done: ["Solo queda el resultado.", "Se saltó un trozo. No preguntes.", "Epitaph lo vio venir."],
      },
    },
    hermit: [
      "Veo… {min} en la página.",
      "Veo… {parts} de {total} partes leídas.",
      "Veo… {secrets} secretos encontrados.",
      "Veo… tu visita número {visits}.",
    ],
    hermitPhoto: { title: "Foto de espíritu", time: "En la página", parts: "Partes leídas", secrets: "Secretos", visits: "Visita" },
    dejaVu: ["…¿Déjà vu?", "Ya dije esto, ¿no?", "Otra vez…"],
    universe: {
      label: "Universo anterior",
      tagline: "Páginas web y software que hacen funcionar tu negocio.",
      badge: "Disponible para proyectos nuevos",
      loading: "Reiniciando el universo",
      stop: ["¡ALTO! Este universo me gusta.", "¿Volver al rojo? ¡Ni loco!", "¡NO! Aquí no había Stands."],
    },
    janken: {
      title: "Jan-ken",
      intro: [
        "Piedra, papel o tijera. Tres rondas.",
        "Boy II Man me enseñó. Tres rondas.",
        "Si ganas, nada. Si pierdo, tampoco.",
        "Tres rondas. Sin poderes. Lo juro.",
        "Elige. Ya sé qué vas a sacar.",
      ],
      hands: { rock: "Piedra", paper: "Papel", scissors: "Tijera" },
      call: "じゃんけんぽん!",
      win: ["¡Ja! Leí tu mente.", "Predecible.", "Tu próxima jugada es… perder.", "Joseph me enseñó.", "Muda."],
      lose: ["Suerte.", "Eso no contó.", "Hm. Interesante.", "¿Usaste un Stand?", "Bien. Por ahora."],
      draw: ["Empate. Otra.", "Pensamos igual. Qué miedo.", "Aiko desho.", "Mismo destino.", "¿Me copiaste?"],
      matchWin: ["Gané. Yare yare daze.", "Victoria. Era obvio.", "Muda muda muda.", "Mi Stand no pierde."],
      matchLose: ["Me ganaste. No se lo digas a él.", "Bien jugado. Revancha.", "…Good.", "Perdí. Pero con estilo."],
      score: "Tú {you} · Stand {me}",
      again: "Revancha",
      close: "Cerrar el juego",
      quit: ["Nigerundayo, ¿eh?", "¿Te vas? Iba ganando.", "¿Huyes? Smokey lo haría."],
    },
  },
  en: {
    label: "Mini Stand: talk to it",
    spots: {
      sites: [
        "All live. None in progress.",
        "Tap one. They don't bite.",
        "He built them. I watched.",
        "I sorted this strip.",
        "Zero templates. All made to fit.",
        "See the baby store? Adorable.",
        "No two look alike.",
        "Open one. It's really live.",
        "Each one, its own Stand.",
        "Real. Domains and all.",
        "A hotel in Santa Marta. Yes.",
        "Even a dog groomer. Woof.",
        "24/7 liquor store. I don't drink.",
        "Truck rentals. ブロロロ.",
        "Eight sites. Eight chapters.",
        "Shoes, babies, dogs. Range.",
      ],
      audit: [
        "Paste your link. No fear.",
        "Free. Suspicious, right?",
        "Your site is staring at me.",
        "I don't judge. Much.",
        "Six checks. Like my fingers.",
        "Daga kotowaru… no, go on.",
        "My Hermit Purple checks too.",
        "If it goes red, wasn't me.",
        "Takes seconds.",
        "A checkup. Like Joseph's.",
        "Slow? We'll find out.",
        "Nothing is stored. Stand's honor.",
        "Your site vs my eye. ゴゴゴ.",
      ],
      about: [
        "That's my user.",
        "One arrow, and here we are.",
        "He types. I exist.",
        "Engineer and editor. Me: Stand.",
        "Security first. Me second.",
        "Read slowly. There's tension.",
        "His dream beats Giorno's.",
        "Destination: Bucaramanga.",
        "His Bizarre Adventure starts here.",
        "He checks locks. Even mine.",
        "He runs carpy. I run nothing.",
        "Logo, colours, content. All of it.",
        "32K on TikTok. I have 0.",
        "This chapter is the origin.",
      ],
      standcard: [
        "That's me. Taller in person.",
        "Potential A. Modesty C.",
        "Speed B. I'm training.",
        "Don't trust the hexagon.",
        "My best angle. That one.",
        "Paranoid Android. Yes, the song.",
        "Tap the arrow. If you dare.",
        "Range A: the whole page.",
        "Precision A. Aim, no idea.",
        "Power C. It's humility.",
        "Durability A. I take your clicks.",
        "My card. My pride.",
        "That arrow made me. Respect.",
      ],
      github: [
        "Every column is a day.",
        "Hit them. They like it.",
        "August woke something up.",
        "I stacked the tall one.",
        "ゴゴゴゴゴ…",
        "Commit after commit. ORA.",
        "Spin it. Epic from behind.",
        "Columns rising. Like me.",
        "A day without commits: yare yare.",
        "Every cube, one ORA.",
        "Tap one, it tells the day.",
        "This is a battle board.",
        "The gold ones shine for a reason.",
      ],
      services: [
        "Pick one. Or all of them.",
        "No templates.",
        "All by hand. Well, keyboard.",
        "Open one. I'll wait.",
        "Something else? Ask him.",
        "From logo to server. All of it.",
        "Every service, its own chapter.",
        "Video too? Yes. He edits.",
        "More useful than a time Stand.",
        "Sites, software, video. Trio.",
        "Like choosing a Stand.",
        "Open the one you need. Just that.",
      ],
      projects: [
        "Three chapters. No filler.",
        "Chapter 2 is my favourite.",
        "Spoiler: they end well.",
        "Not an anime. It's real.",
        "Switch tabs. There's more.",
        "Real screenshots. No tricks.",
        "Ending: To be continued.",
        "Chapter 3 isn't bad either.",
        "King Crimson saw all of this.",
        "Records found in seconds.",
        "Every case, a fight won.",
        "Read the whole chapter. Worth it.",
      ],
      pricing: [
        "Prices out in the open.",
        "Cheaper than an arrow.",
        "The middle one is the chosen.",
        "Nigerundayo… no, stay.",
        "Final price agreed up front.",
        "Extras are written down.",
        "Speedwagon would approve.",
        "No fine print. No ゴゴゴ.",
        "Take your time. No pressure.",
        "The domain is in your name.",
        "No surprises. Except me.",
        "Compare. I'll hold the table.",
      ],
      faq: [
        "Ask anything.",
        "I read them all. Twice.",
        "Not there? Message him.",
        "Open them. They won't explode.",
        "Short and to the point.",
        "My answers: ORA. His are better.",
        "Unsure? Open another.",
        "Hermit Purple read them already.",
        "Works all over Colombia. And abroad.",
        "Spanish or English. Both.",
        "No silly questions here.",
      ],
      contact: [
        "Write. I'll let him know.",
        "He usually replies same day.",
        "One message. Just one.",
        "WhatsApp or email. Your call.",
        "You made it this far…",
        "Say it. ゴゴゴ.",
        "He reads everything. So do I.",
        "The chapter closes here.",
        "Your turn. I've talked enough.",
        "Writing is free.",
        "Tell your idea. He builds it.",
        "Fate brought you here.",
      ],
      tbc: [
        "To be continued…",
        "End of Part 9.",
        "Arrivederci. Or not.",
        "Scroll up. There's more.",
        "Hear Roundabout?",
        "The arrow points up. Go.",
        "The end. Or a new beginning.",
        "Next part: you write it.",
        "Credits. Stay for the extra scene.",
      ],
    },
    outro: [
      "Don't you get tired? I do.",
      "I'm out of lines. Muda.",
      "From the top. Yare yare.",
      "Said it all here. Move along.",
      "Repeating is Bites the Dust's job.",
    ],
    sleep: "z z z",
    wake: [
      "I wasn't asleep!",
      "I was meditating. Hamon.",
      "Huh? You're back?",
      "Strategic pause.",
      "I stopped my own time.",
      "Dreamt of a capybara.",
      "Awake! What did I miss?",
      "Dreamt I was Star Platinum.",
      "Five more minutes… no. Ready.",
      "Recharging Stand energy.",
      "Asleep? That was a pose.",
    ],
    home: ["Home.", "Back to the portrait.", "Nice spot.", "Back to the origin.", "My favourite corner.", "Guarding the portrait."],
    night: "Night shift. Like DIO.",
    console: "You called me? Nobody does that.",
    greetings: {
      morning: ["Morning. Coffee or Hamon?", "Early. Like Jonathan.", "The sun is up. Ugh.", "Early bird. Respect.", "Good morning. Breathe. Hamon."],
      afternoon: [
        "Good afternoon. Reading time.",
        "An afternoon of Stands. Good pick.",
        "Nap cancelled. Let's go.",
        "Perfect afternoon for a chapter.",
        "Had lunch? I don't eat.",
      ],
      evening: [
        "Good evening. Stand hours.",
        "Reads better at night.",
        "Night falls. I wake up.",
        "DIO's hour. I mean, reading hour.",
        "Night. Perfect mood. ゴゴゴ.",
      ],
      visit: ["You're back. Visit {n}.", "Visit {n}. Family now.", "{n} visits. Suspicious. I like it.", "Visit {n}. One more Joestar.", "You again. Visit {n}."],
    },
    musings: [
      "Did you know I have no legs?",
      "What would Jotaro do here?",
      "This layout has a good pose.",
      "Smells like ゴゴゴ around here.",
      "Tap me and we talk.",
      "I think, therefore Stand.",
      "Someday I'll be in the anime.",
      "Still here. Just in case.",
      "Pose time. Ready? No.",
      "Want me to stop time? Ask.",
      "You can throw me. Please don't.",
      "My diamond shines on its own.",
      "I have ten borrowed powers.",
      "Tried Soft & Wet? Bubbles.",
      "Bored. Can I break something?",
      "Drag me and I get dizzy.",
      "Every section has its mood.",
      "Read all this. Three times.",
      "This pixel is my good side.",
      "Shh. I sense an enemy Stand.",
    ],
    landing: ["ドン!", "ドドド", "バァーン", "ゴゴゴ", "ズン", "ドーン", "シュタッ", "ババーン"],
    events: {
      timestop: [
        "I couldn't move…!",
        "Who stopped time? You?",
        "You froze me. Eternal grudge.",
        "Not even I escape that clock.",
        "Only DIO does that!",
        "Five seconds of not existing. Ugh.",
      ],
      ora: ["ORA ORA ORA!", "Yes! Harder.", "You typed ora? Respect.", "Jotaro would be proud.", "ORAAA! That's how you spell it."],
      muda: ["MUDA? That's DIO's.", "Traitor.", "Wryyyy… sorry.", "Muda muda… Giorno, is that you?", "You type like a villain."],
      tbc: ["To be continued…", "That's it? That's the ending?", "Roundabout playing.", "The arrow. Always the arrow.", "Season finale."],
      barrage: ["That's the barrage!", "Six hits. Not bad.", "The columns are crying.", "ORA at the commits!", "That column won't recover."],
      arrow: ["That arrow! That's how I was born.", "Careful. It stings.", "Not another Stand, please.", "The arrow chooses. It chose you.", "Woke something up? ゴゴゴ."],
      themeLight: ["My eyes! The light!", "Day mode? I'm a night Stand.", "Is this DIO's sun… no.", "Shiny. Like my diamond.", "Ugh. Pure Hamon."],
      themeDark: ["Better. The night is mine.", "There. Dark and classy.", "Ahh. Peace.", "Night is back. Wryyy.", "My pixels can breathe."],
      language: ["Language swap. Interesting.", "I speak both. Obviously.", "Bilingual. Like him.", "New language. Same Stand."],
      whatsapp: ["Yes! Message him.", "Good call. ゴゴゴ.", "I'll tell him you're coming.", "That's the spirit!", "Fate sealed. ドン!"],
      copy: ["Copying? Respect.", "Take it. It's free.", "Ctrl+C. Classic.", "Echoes already recorded it.", "Copied. Like a twin Stand."],
      return: ["Where were you?", "I waited. Very still.", "You're back. Knew it.", "Another tab? Jealous.", "King Crimson erased your absence."],
      fastScroll: ["Slow down! I'm dizzy.", "Hey! This isn't Speed King.", "Wooo… why so fast?", "Made in Heaven or what?", "You're leaving me behind!"],
      stare: ["What are you looking at?", "Yes, it's me.", "Tap me if you dare.", "Oh? You're approaching me?", "Joestar stare. I know it."],
      audit: ["Checking… ゴゴゴ.", "Let's see that site…", "Hermit Purple, show me!", "Analysing. Don't move."],
      sent: ["Sent! He'll reply.", "Message delivered. Nice.", "Now we wait. I'll wait with you.", "Perfect! ドン!", "Done. Fate is moving."],
      bottom: ["You reached the end. Respect.", "You read it all. You're one of us.", "End of the volume. Nice.", "All read. Joestar medal."],
      chapter: ["New chapter!", "Next episode. ドン!", "Oh, good chapter.", "I like that case.", "Turn the page. ペラ."],
      faq: ["Good question.", "I wondered that too.", "Read it all. It's short.", "Answer unlocked.", "Joestar curiosity."],
      hesitate: ["Hesitating? Go on.", "That button doesn't bite.", "One click. I've got you.", "Courage. Like Jonathan.", "Nigerundayo… no. Click."],
      typing: ["Type away. I'm not looking.", "Take your time.", "That's it. No fear.", "You type like ORA.", "Echoes is listening. Relax."],
      resize: ["Shrinking me? Hey.", "The page stretches. I don't.", "The Hand? Everything moved.", "New window. Same me."],
      thrown: ["WRYYYYY!", "Hey! I'm dizzy!", "I'm not a ball!", "Everything's spinning…", "Nigerundayo… ah!", "Put me down, human!"],
      dropped: ["Put me down! Oh, ok.", "Elegant landing.", "You moved me? Brave.", "Thanks for the ride.", "Nice view from here."],
    },
    timeStop: {
      sections: {
        hero: ["I touched your portrait. You missed it.", "Strolled the hero. All frozen.", "Not even WhatsApp moved. I did."],
        sites: ["Checked all eight sites. You: frozen.", "Visited them all. You didn't see.", "The strip stopped. I didn't."],
        audit: ["Audited while you couldn't.", "Your link waited. I didn't.", "Scan paused. Muda."],
        about: ["Read his whole story. Done.", "Not even he moved. I did.", "I moved. Did you notice?"],
        standcard: ["Speed B… and still I moved.", "Posed for the arrow.", "My card and me. The only ones."],
        github: ["Not one commit moved.", "Counted every column.", "Board frozen. I'm free."],
        services: ["Picked one for you. Kidding.", "The services waited. I didn't.", "Service pause. Ha."],
        projects: ["Paused the chapter. Read the end.", "The case stopped. I didn't.", "Not even King Crimson moved."],
        pricing: ["I froze the prices. Literally.", "No price went up. You're welcome.", "Touched the table. You missed it."],
        faq: ["Read every answer. Done.", "The questions didn't open.", "I paused curiosity."],
        contact: ["Your message waited. Still.", "Not even the form blinked.", "I'm here already. You're not."],
        tbc: ["To be… paused.", "The arrow didn't advance.", "Roundabout on pause."],
        default: ["Nobody moved. Except me.", "Just me in that world.", "Muda muda. You were frozen.", "Saw anything? No. Nothing."],
      },
      attempt: [
        "You tried to move. I saw.",
        "Your finger didn't respond, huh?",
        "Muda. I saw you try.",
        "Wanted to scroll? Cute.",
        "Not a pixel. You tried.",
      ],
      resume: ["そして時は動き出す。", "And time moves again.", "Did I move? Never.", "I was always here.", "Time, carry on.", "Nine seconds. Personal best."],
    },
    chat: {
      title: "Paranoid Android",
      close: "Close the conversation",
      greet: [
        "Oh? Are you talking to me?",
        "A human tapped me. What do you want?",
        "Speak. Time is running. Unless I stop it.",
        "Yes? I was posing.",
        "Ah! A brave visitor.",
        "Paranoid Android, at your service.",
        "You touched me. Now we're allies.",
        "Need a Stand? Here I am.",
      ],
      greetAgain: ["You again? I like you.", "Back. I knew you would be.", "It was our fate to talk again.", "We're friends now, right?", "You again. ゴゴゴ. Welcome."],
      options: {
        who: "Who are you?",
        cris: "Tell me about him",
        guide: "Take me to…",
        trivia: "Some JoJo trivia",
        power: "Use a power",
        janken: "Let's play jan-ken",
        bye: "Nothing, carry on",
      },
      who: [
        ["I'm Paranoid Android.", "Cristian's Stand.", "Born from an arrow. Long story."],
        ["A Stand. Spirit turned power.", "He codes. I exist, with style."],
        ["They call me PA.", "Well, nobody calls me anything.", "You could be the first."],
        ["I live on this page.", "I sleep on the portrait.", "And perch on what you read."],
        ["I have borrowed powers.", "None are mine, technically.", "But I use them with style."],
        ["My diamond is my heart.", "Diamond is Unbreakable.", "Neither am I. I think."],
      ],
      cris: [
        "He builds websites, software and video.",
        "Lives in Bucaramanga. Works remote.",
        "Co-founded carpy, a software studio.",
        "Comes from cybersecurity. Checks the locks.",
        "Has 32K+ followers built on his own content.",
        "Works in Spanish and English.",
        "Message him on WhatsApp; he usually replies same day.",
        "Has eight live websites for businesses.",
        "He built one for a hotel in Santa Marta.",
        "Works with businesses all over Colombia and abroad.",
        "The domain and hosting stay in the client's name.",
        "Uses the tool the problem needs, not the habit.",
        "Also does logo, colours and content.",
        "Built a records search that finds them in seconds.",
        "Talks over WhatsApp or video call.",
      ],
      trivia: [
        "JoJo started in 1987. Araki doesn't age. Suspicious.",
        "Since Part 4, Stands are named after songs.",
        "I'm named after a Radiohead song. Tradition.",
        "The JoJo pose has a name: JoJo-dachi.",
        "ゴゴゴ is the sound of tension. Literally.",
        "Every Joestar has a star birthmark on the shoulder.",
        "DIO slept a hundred years at the bottom of the sea.",
        "You learn Hamon by breathing. I don't breathe.",
        "Yes's Roundabout closed the anime. To be continued.",
        "Jotaro says yare yare daze when he's annoyed.",
        "Speedwagon always withdraws in style.",
        "Killer Queen is named after a Queen song.",
        "Bites the Dust: another Queen song.",
        "Crazy Diamond comes from Pink Floyd.",
        "Kira just wanted a quiet life. Sure.",
        "Josuke gets angry if you mock his hair.",
        "Only Stand users can see Stands.",
        "Joseph guesses what you'll say. Always.",
        "Gold Experience gives life to what it hits.",
        "Part 3 Stands come from tarot cards.",
        "Rohan draws faster than you read this.",
        "Polnareff has the tallest hair in JoJo.",
      ],
      guidePrompt: ["Where to? I fly, you watch.", "Pick a destination. Hold on.", "Where are we going, partner?", "Destination. Choose wisely."],
      guide: {
        projects: { label: "His projects", say: ["To the chapters!", "Projects. Hold tight.", "To the cases. ドン!"] },
        sites: { label: "The websites", say: ["Live websites. Let's go!", "To the strip of sites.", "Eight sites. Fly!"] },
        pricing: { label: "The prices", say: ["Prices. No fear.", "Straight to the point.", "To the table. Breathe."] },
        contact: { label: "Talk to him", say: ["To the contact! ドン!", "Good call. Let's go.", "Straight to him. Go!"] },
      },
      powerPrompt: [
        "I have borrowed powers. Pick.",
        "Pick one. Not my fault after.",
        "Which? They're all dangerous.",
        "Ten Stands in one. Pick.",
        "Choose. I'll do the pose.",
      ],
      bye: ["Arrivederci.", "I'll go perch somewhere.", "Yare yare. Bye.", "See you next chapter.", "Sayonara. ゴゴゴ.", "I'll be here. Posing."],
      back: "Something else",
    },
    powers: {
      zawarudo: {
        name: "ZA WARUDO",
        jp: "時よ止まれ",
        say: ["ZA WARUDO!", "ZA WARUDO! Toki yo tomare!", "My world. ZA WARUDO!"],
        done: ["And time moves again.", "そして時は動き出す。", "Saw anything? No, nothing.", "Five seconds of mine."],
      },
      starplatinum: {
        name: "Star Platinum",
        jp: "オラオラ",
        say: ["ORA ORA ORA ORA!", "Star Platinum… ORA!"],
        done: ["Yare yare daze.", "Full barrage. Nothing broken.", "That's how Jotaro hits. Roughly."],
        variants: {
          rush: { say: ["ORA ORA ORA ORA!", "Star Platinum… ORA!", "ORA rush!"], done: ["Yare yare daze.", "Dented. It fixes itself.", "Full barrage."] },
          finger: { say: ["Star Finger!", "Star Platinum… star finger!"], done: ["One precise poke.", "Precision A. See?"] },
          world: { say: ["Star Platinum: The World!", "I can stop time too."], done: ["One second of mine.", "Like DIO. But nice."] },
        },
      },
      crazydiamond: {
        name: "Crazy Diamond",
        jp: "ドラララ",
        say: ["DORARARARA!", "Crazy Diamond… DORA!", "Doraaaa!"],
        done: ["Broken and fixed. Good as new.", "Crazy Diamond leaves it better.", "What did you say about my hair?", "All in place. Almost."],
      },
      goldexperience: {
        name: "Gold Experience",
        jp: "生命を",
        say: ["Gold Experience. Life!", "I, Giorno… no. But close."],
        done: ["The page is alive. Literally.", "Life for everyone."],
        variants: {
          garden: { say: ["Gold Experience. Life!", "Let it all bloom!"], done: ["Ladybugs included. You're welcome.", "Instant spring."] },
          tree: { say: ["Gold Experience… a tree!", "Grow!"], done: ["A whole tree. Photosynthesis.", "That tree gives shade already."] },
          frog: { say: ["That box… will be a frog!", "Gold Experience. Ribbit!"], done: ["It was a box. Now it hops.", "The frog is a box again. Relax."] },
          butterflies: { say: ["Butterflies! Pure life.", "Gold Experience… fly!"], done: ["They flew away. Free.", "Pure life. Literally."] },
          snake: { say: ["That title… a snake!", "Gold Experience. Sssss."], done: ["A title again. Phew.", "It doesn't bite. I think."] },
        },
      },
      echoes: {
        name: "Echoes",
        jp: "エコーズ",
        say: ["Echoes! Stuck-on sounds."],
        done: ["Now the page has sound.", "They peel off by themselves."],
        variants: {
          act1: { say: ["Echoes ACT 1! Living sounds.", "Sticking sounds. Watch them ring."], done: ["The page spoke. Literally.", "Sounds returned."] },
          act2: { say: ["ACT 2! Touch them. They ring.", "Echoes ACT 2. Step on one."], done: ["Touched them all? Nice.", "Peeled off. Silence."] },
          act3: { say: ["ACT 3! 3 FREEZE!", "S-H-I-T… I mean, 3 FREEZE!"], done: ["Heavy, huh? It's over.", "Normal weight again."] },
        },
      },
      softwet: {
        name: "Soft & Wet",
        jp: "シャボン",
        say: ["Soft & Wet. Thieving bubbles!", "Bubbles. They steal. Pop them."],
        done: ["They took things. I gave them back.", "Free bubbles. All returned."],
        bonus: ["All of them! You got it all back.", "None escaped. Gappy would be proud.", "Popped them all. Thief of thieves."],
      },
      hermit: {
        name: "Hermit Purple",
        jp: "ハーミット",
        say: ["Hermit Purple… let's see.", "Hermit Purple! Spirit photo."],
        done: ["Photo developed. Keep it in mind.", "Joseph would be proud."],
      },
      madeinheaven: {
        name: "Made in Heaven",
        jp: "時は加速する",
        say: ["Made in Heaven! Time speeds up.", "Made in Heaven… faster!"],
        done: ["Phew. Universe saved.", "This universe stays.", "Almost back to red. Never again."],
      },
      bitesthedust: {
        name: "Bites the Dust",
        jp: "負けて死ね",
        say: ["Killer Queen… Daisan no bakudan!", "Killer Queen… Bites the Dust!"],
        done: ["Time went back. Nobody noticed.", "Déjà vu? Normal.", "Another one bites the dust."],
      },
      kingcrimson: {
        name: "King Crimson",
        jp: "キング・クリムゾン",
        say: ["King Crimson!", "King Crimson… erase time."],
        done: ["Only the result remains.", "A chunk got skipped. Don't ask.", "Epitaph saw it coming."],
      },
    },
    hermit: [
      "I see… {min} on this page.",
      "I see… {parts} of {total} parts read.",
      "I see… {secrets} secrets found.",
      "I see… your visit number {visits}.",
    ],
    hermitPhoto: { title: "Spirit photo", time: "On the page", parts: "Parts read", secrets: "Secrets", visits: "Visit" },
    dejaVu: ["…déjà vu?", "Didn't I say this?", "Again…"],
    universe: {
      label: "Previous universe",
      tagline: "Websites and software that make your business run.",
      badge: "Available for new projects",
      loading: "Resetting the universe",
      stop: ["STOP! I like this universe.", "Back to red? No way!", "NO! There were no Stands there."],
    },
    janken: {
      title: "Jan-ken",
      intro: [
        "Rock, paper, scissors. Best of three.",
        "Boy II Man taught me. Best of three.",
        "Win and you get nothing. Same as me.",
        "Three rounds. No powers. Promise.",
        "Pick. I already know your move.",
      ],
      hands: { rock: "Rock", paper: "Paper", scissors: "Scissors" },
      call: "じゃんけんぽん!",
      win: ["Ha! Read your mind.", "Predictable.", "Your next move is… losing.", "Joseph taught me.", "Muda."],
      lose: ["Lucky.", "That didn't count.", "Hm. Interesting.", "Did you use a Stand?", "Fine. For now."],
      draw: ["Draw. Again.", "Same mind. Scary.", "Aiko desho.", "Same fate.", "Did you copy me?"],
      matchWin: ["I win. Yare yare daze.", "Victory. Obviously.", "Muda muda muda.", "My Stand doesn't lose."],
      matchLose: ["You beat me. Don't tell him.", "Well played. Rematch.", "…Good.", "I lost. With style, though."],
      score: "You {you} · Stand {me}",
      again: "Rematch",
      close: "Close the game",
      quit: ["Nigerundayo, huh?", "Leaving? I was winning.", "Running? Smokey would."],
    },
  },
};
